### ISSUE TITLE
Section 3 - "Monte Carlo simulations"

### ISSUE THREAD

**Issue by dou-du** [osscar-org/quantum-mechanics#6]
**Source code**: https://github.com/osscar-org/quantum-mechanics/blob/develop/notebook/statistical-mechanics/monte_carlo_parabolic.ipynb

- [x] polish the texts
- [x] check the codes

**Comment by giovannipizzi** [comment]
A few things to do after merging:
- [ ] add one new slider to select the number of initial points to skip (now the value is hardcoded). I would keep the default to zero and have the slider go from e.g. 0 to 50000. The description could be "skip first # steps:". After this, note that there might need to be some adaptation to the text (e.g. the legend)
- [ ] when the run is done, to the right of the Run button, add a text "Acceptance rate: XX%", where XX is computed as the % of moves that were accepted.
